### ISSUE TITLE
The DiAbstractServiceFactory causes recursion

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-servicemanager-di#2]
I'm using the `\Zend\ServiceManager\Di\DiAbstractServiceFactory` to initialize objects and resolve their dependencies. But I have an issue with recursion in the `\Zend\ServiceManager\ServiceManager::has`.

I've added the `\Zend\ServiceManager\Di\DiAbstractServiceFactory` (it's also not a trivial task because service manager calls `new` during abstract factory [initialization](https://github.com/zendframework/zend-servicemanager/blob/master/src/ServiceManager.php#L522)) to list of abstract factories.

During object initialization by `ServiceManager` via `DiAbstractServiceFactory` the `\Zend\ServiceManager\Di\DiServiceFactory::get` will be called to create the object and this method calls `\Zend\ServiceManager\ServiceManager::has` to check if `ServiceManager` can create this object; in its turn `ServiceManager` [will check](https://github.com/zendframework/zend-servicemanager/blob/master/src/ServiceManager.php#L244) if configured abstract factories have possibility to create this object.

This behavior in the couple of [\Zend\ServiceManager\Di\DiServiceFactory::get](https://github.com/zendframework/zend-servicemanager-di/blob/master/src/DiServiceFactory.php#L129) implementation causes the circular recursion. The previous implementation of `\Zend\ServiceManager\ServiceManager::has` was [smarter](https://github.com/zendframework/zend-servicemanager/blob/release-2.7/src/ServiceManager.php#L716) and didn't have this issue.

Specifying `\Zend\ServiceManager\Di\DiServiceFactory::USE_SL_AFTER_DI` during `DiAbstractServiceFactory` doesn't solve this issue because other dependencies cannot be resolved.

`zend-servicemanager-di 1.1.0`
`zend-servicemanager 3.3.0`

---

Originally posted by @joni-jones at https://github.com/zendframework/zend-servicemanager/issues/186

**Comment by samsonasik** [comment]
@boesing I transfered the issue, there is button for that

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> You can now [use laminas/laminas-di directly with laminas/laminas-servicemanager](https://docs.laminas.dev/laminas-di/v3/cookbook/use-with-servicemanager/).
